//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaago.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chef
    {
        public int Chef_ID { get; set; }
        public string Chef_Name { get; set; }
        public string Chef_Email { get; set; }
        public string Chef_Contact { get; set; }
        public string Msg_Body { get; set; }

        //public bool IsSelectedForDeletion { get; set; }
    }
}
