//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaago.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Details = new HashSet<Order_Details>();
            this.Order_Details1 = new HashSet<Order_Details>();
        }
    
        public int orderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string orderTime { get; set; }
        public string orderDate { get; set; }
        public string orderStatus { get; set; }
        public string numberOfItems { get; set; }
        public string Amount { get; set; }
        public string deliveryCharges { get; set; }
        public string City { get; set; }
        public string notes { get; set; }
        public bool IsSelectedForDeletion { get; set; }
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details1 { get; set; }
    }
}
